---

# The CERNVM GPG key is the trust anchor for the secure installation of the CVMFS client.
#
# The Compute Canada CVMFS GPG key is the trust anchor for the secure distribution of the Compute Canada software stack (and other content), as follows:
#	- the Compute Canada CVMFS GPG key verifies the authenticity of the computecanada-release RPM
#	- the computecanada-release RPM configures a yum repository which distributes the cvmfs-config-computecanada RPM
#	- the cvmfs-config-computecanada RPM contains the public CVMFS key for the cvmfs-config.computecanada.ca CVMFS configuration repository
#	- the CVMFS configuration repository contains the public CVMFS keys for all other Compute Canada CVMFS repositories
#	- the other CVMFS repositories contain all Compute Canada software (and other content)

- name: Install CernVM GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    state: present
    validate_certs: yes
    fingerprint: "{{ item.fingerprint }}"
  loop:
    # 2024
    - { key: "https://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM-2048", fingerprint: "FD80 468D 49B3 B24C 3417  41FC 8CE0 A76C 497E A957" }
    # older key, to be eventually removed
    - { key: "https://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM",      fingerprint: "70B9 8904 8820 8E31 5ED4  5208 230D 389D 8AE4 5CE7" }

# Also available at https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/RPM-GPG-KEY-CC-CVMFS-1
- name: Install Compute Canada CVMFS GPG key
  rpm_key:
    key: https://package.computecanada.ca/yum/cc-cvmfs-public/RPM-GPG-KEY-CC-CVMFS-1
    state: present
    validate_certs: yes
    fingerprint: "C0C4 0F04 70A3 6AF2 7CC4  4D5A 3B9F C55A CF21 4CFC"
  when: '"cvmfs-config-computecanada" in cvmfs_configuration'
